services:
  selenium-chrome:
    image: selenium/standalone-chrome
    environment:
      - SE_NODE_SESSION_TIMEOUT=32000000
    ulimits:
      nofile: 32768

  app:
    build:
      context: ./images/app
    environment:
      - TOKEN=${TOKEN}
      - SELENIUM=http://selenium-chrome:4444
    depends_on:
      - selenium-chrome
    env_file:
      - path: ./.env
        required: true
    restart: unless-stopped
